### ISSUE TITLE
Issue while creating deis cluster with this script

### ISSUE THREAD

**Issue by arv1989** [chanezon/azure-linux#15]
Command used 
./azure-coreos-cluster xxxxxxxx \
--ssh-cert ~/xxxxxxxx/ssh-cert.cer \
--ssh-thumb xxxxxxxx \
--subscription xxxxxxxx \
--azure-cert ~/xxxxxxxx/azure-cert.pem \
--num-nodes 5 \
--location "xxxxxxxx" \
--vm-size Large \
--vm-name-prefix xxxxxxxx \
--virtual-network-name "xxxxxxxx" \
--availability-set xxxxxxxx \
--deis \
--pip \
--data-disk \
--blob-container-url https://xxxxxxxx.windows.net/vhds/

ERROR: 

{'status': u'Failed', 'error': <azure.servicemanagement.OperationError object at 0x111201290>, 'id': u'', 'http_status_code': u'400'}
BadRequest
{'message': u"The subscription policy limit for resource type 'public IP count' was exceeded. The limit for resource type 'public IP count' is 5 per subscription, the current count is 5, and the requested increment is 1.", 'code': u'BadRequest'}
Failed
create VM tlepro-tle_-0 took: 15s
Traceback (most recent call last):
  File "./azure-coreos-cluster", line 216, in <module>
    role_size=args.vm_size, network_config=network, data_virtual_hard_disks=data_disks)
  File "/Library/Python/2.7/site-packages/azure/servicemanagement/servicemanagementservice.py", line 1342, in add_role
    async=True)
  File "/Library/Python/2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 235, in _perform_post
    response = self.perform_post(path, body, x_ms_version)
  File "/Library/Python/2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 162, in perform_post
    response = self._perform_request(request)
  File "/Library/Python/2.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 192, in _perform_request
    return _management_error_handler(ex)
  File "/Library/Python/2.7/site-packages/azure/servicemanagement/__init__.py", line 1811, in _management_error_handler
    return _general_error_handler(http_error)
  File "/Library/Python/2.7/site-packages/azure/__init__.py", line 924, in _general_error_handler
    _ERROR_NOT_FOUND.format(str(http_error)))
azure.WindowsAzureMissingResourceError: Not found (Not Found)

**Comment by chanezon** [comment]
--pip uses public ip addresses. In Azure, right now, these are limited to 5 per subscription. cf https://msdn.microsoft.com/en-us/library/azure/dn690118.aspx

This may change in the future. In order to avoid that issue, delete all machines using a pip now, and you can provision one cluster with 5 machines using --pip for deis.
